version: '3.1'

services:

  db:
    bimage: postgres
    #ostname: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./databases:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pwdpwd
    ports:
      - 80:80
    