version: '3.1'

services:

  db:
    image: postgres
    #container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./databases:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pwdpwd
    volumes:
      - ./settings/servers.json:/pgadmin4/servers.json
    ports:
      - 80:80   